### ISSUE TITLE
fix: create new chatroom from search functionality 

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#203]
currently: 
- spinner continues to spin when searching for a chatroom that does not exist 
- 'No results. Would you like to create this chatroom?' never appears 
- '+' icon never appears 

- search & add does NOT work on category chats; only searching works
- both search and search & add work on partner chats

**Comment by lkobetz** [comment]
So, to clarify, users should be able to add a new chatroom to the category chats. For example, in 'Matrescence' they could add a new chatroom called 'SecondTrimester'?
