### ISSUE TITLE
delete message functionality on reply bar

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#215]
- add delete message functionality to reply bar
- this functionality mirrors that of the flagging functionality in that the message will be overwritten with text that states "The user has deleted this message."
- The delete functionality will differ from flagging in that users CANNOT long press to view the message that was previously displayed.

**Comment by lkobetz** [comment]
What should the delete icon be? a trash can?

**Comment by lisjak** [comment]
> What should the delete icon be? a trash can?

Yep, trash-2 from Feather looks good.

`<Feather name="trash-2" size={15} color="lightgrey" />`

**Comment by lkobetz** [comment]
awesome! thanks!
