### ISSUE TITLE
sign-up-page

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#3]
[ ] email
[ ] username
[ ] password
[ ] birthday dropdown
[ ] time-zone dropdown
[ ] Dropdown select: Hopeful Parent; Donor; New Mother; Parent
[ ] Sign up (submit) button

**Comment by malkamoskowicz** [comment]
Functionality complete. Not utilizing the time-zone field or dropdown menus for now, but we can definitely incorporate that in the future.
