### ISSUE TITLE
user-class-identification

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#68]
* allow users to ID as:
1. New Mother 
2. Surrogate
3. Gestational Carrier
4. Adoptive Parent
5. Hopeful Parent
6. Parent
7. Egg/Embryo Donor
8. New Parent
9. Parent Recovering from Loss
10. Other
11. Prefer not to Disclose

* when signing up (drop down menu)
* allow users to change class ID on user page
* create role-based message boards

**Comment by malkamoskowicz** [comment]
Good first issue: Adding the dropdown to the signup page and making sure it is accurately added to the database.

**Comment by featherweightdev** [comment]
https://github.com/lawnstarter/react-native-picker-select
