### ISSUE TITLE
signup-popup

### ISSUE THREAD

**Issue by lisjak** [zoot-hq/zoot#96]
- When a New User signs up, have a Pop Up w Button to Agree to Community Guidelines

Community Guidelines

1.	Après is intended to be a place of acceptance, empathy and compassion Above all else, try to be kind. 
2.	Think before you type.
3.	If you see something unacceptable, please flag the comment for review. 
4.	If you experience a user who repeatedly behaves in an unacceptable manner, please flag the user for review.
5.	If you are struggling in a way that feels overwhelming, please see our resources for access to professional mental healthcare providers, and get help.
6.	We are open and love your feedback.  Please send us your suggestions on how to improve your experience.

**Comment by malkamoskowicz** [comment]
Library already used elsewhere in our project that might be useful here: https://github.com/react-native-community/react-native-modal

**Comment by featherweightdev** [comment]
Double check the text (see wireframes), match design to wireframes
